# One-off run: define tables and checks
datasets:
  - table: BANK_DB.branches
    null_check:
      columns: [branch_id, branch_name, governorate, branch_address, latitude, longitude]
    range_check:
      columns:
        - column: latitude
          min: -90.0
          max: 90.0
          inclusive: true
        - column: longitude
          min: -180.0
          max: 180.0
          inclusive: true
    uniqueness_check:
      columns: [branch_id]

  - table: BANK_DB.transactions
    null_check:
      columns: [transaction_id, transaction_currency, transaction_type, transaction_amount, branch_id]
    range_check:
      columns:
        - column: transaction_amount
          min: 0
          max: 99999.99
    uniqueness_check:
      columns: [transaction_id]
