swagger: '2.0'
info:
  title: Streamable HTTP MCP Server Azure Reverse Tunnel
  description: >-
    This is a MCP server running locally and exposed via streamable HTTP using a
    reverse SSH tunnel through an Azure-hosted VM.
  version: 1.0.0
host: 20.33.77.25:8001
basePath: /
schemes:
  - http
consumes: []
produces: []
paths:
  /mcp/:
    post:
      x-ms-agentic-protocol: mcp-streamable-1.0
      operationId: TeradataMCP
      consumes:
        - application/json
      produces:
        - application/json
        - text/event-stream
      parameters:
        - in: header
          name: Accept
          required: true
          type: string
          default: application/json, text/event-stream
          x-ms-visibility: internal
        - in: header
          name: Content-Type
          required: true
          type: string
          default: application/json
          x-ms-visibility: internal
      responses:
        '200':
          description: Success
securityDefinitions: {}
